# Generated by Django 4.0.5 on 2022-06-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='verification_code_creted_at',
            new_name='verification_code_created_at',
        ),
    ]
